variables:
  BASE_IMAGE: steldermann/quarto:latest

image: $BASE_IMAGE

stages:
  - build_and_deploy
  

pages:
  stage: build_and_deploy

  script:
    - cd ./scripts
    - cat install.sh | /bin/bash 
    - cat build.sh | /bin/bash
    - cd ..
    - mv _html public
  artifacts:
    paths:
      - public/
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


