name: Quarto Build & Deploy

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out your repository
      - name: Check out repository
        uses: actions/checkout@v3

         # --- Check Quarto ---
      - name: Check if Quarto is installed
        run: |
          if quarto --version >/dev/null 2>&1; then
            echo "QUARTO_EXISTS=true" >> $GITHUB_ENV
          else
            echo "QUARTO_EXISTS=false" >> $GITHUB_ENV
          fi

      # --- Check micromamba ---
      - name: Check if micromamba is installed
        run: |
          if micromamba --version >/dev/null 2>&1; then
            echo "MICROMAMBA_EXISTS=true" >> $GITHUB_ENV
          else
            echo "MICROMAMBA_EXISTS=false" >> $GITHUB_ENV
          fi

      # Install micromamba (optional environment file, channels, etc., can be specified if desired)
      - name: Install micromamba
        if: env.MICROMAMBA_EXISTS == 'false'
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          init-shell: bash

      # Install Quarto
      - name: Install Quarto
        if: env.QUARTO_EXISTS == 'false'
        uses: quarto-dev/quarto-actions/setup@v2

      # Render the Quarto project
      - name: Render Quarto project
        run: micromamba run -n quarto_project quarto render

      # Deploy to GitHub Pages (make sure your repo is configured to publish from the gh-pages branch)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _html   # or _book, depending on your Quarto output
          publish_branch: gh-pages
